"""removed-users-serialization

Revision ID: 85bf336f38c1
Revises: 5f16cc1a69e7
Create Date: 2024-08-13 16:08:50.964471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85bf336f38c1'
down_revision = '5f16cc1a69e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('employee')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=80), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('phonenumber',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_column('department')

    with op.batch_alter_table('leave_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_name_column', sa.String(length=160), nullable=False))

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_column('employee_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_name', sa.VARCHAR(length=120), nullable=False))

    with op.batch_alter_table('leave_allocation', schema=None) as batch_op:
        batch_op.drop_column('employee_name_column')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('phonenumber',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('role')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee', sa.VARCHAR(), nullable=True))

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('roles', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
